/**
 * @file sysid_signals.h
 * @brief Excitation signal design for system identification (L2 Concepts, L6 Canonical Problems)
 *
 * Knowledge coverage:
 *   L2 - Persistence of excitation (PE) condition of order n
 *   L2 - Informative experiment design
 *   L2 - Input signal spectrum shaping for identification
 *   L4 - Persistently exciting signals and identifiability
 *   L6 - PRBS (Pseudo-Random Binary Sequence) design
 *   L6 - Multisine signal design with crest factor optimization
 *   L6 - Chirp (swept sine) signal for frequency sweep
 *   L6 - Step response for first-order system ID
 *   L6 - RBS (Random Binary Signal)
 *
 * A signal u(k) is persistently exciting of order n if its covariance matrix
 * R_u(n) = E[φ_n(k) φ_n(k)ᵀ] > 0 (positive definite), where
 * φ_n(k) = [u(k-1), ..., u(k-n)]ᵀ.
 * This is necessary and sufficient for consistent LS estimation of an n-th order FIR.
 *
 * References:
 *   Ljung (1999) §13.2 (Input Design)
 *   Söderström & Stoica (1989) Ch. 9 (Experiment Design)
 *   Godfrey, K. (1993) "Perturbation Signals for System Identification"
 */

#ifndef SYSID_SIGNALS_H
#define SYSID_SIGNALS_H

#include "sysid_types.h"

/*---------------------------------------------------------------------------
 * L6: Pseudo-Random Binary Sequence (PRBS)
 *
 * PRBS is generated by a linear feedback shift register (LFSR) of length m.
 * Period = 2^m - 1, clock period = T_clk.
 * It approximates white noise and is PE of order 2^m - 1.
 *---------------------------------------------------------------------------*/

/** PRBS generator state */
typedef struct {
    int     *taps;       /**< LFSR tap positions [n_taps] */
    int      n_taps;     /**< Number of taps (>=1) */
    int      reg_length; /**< LFSR register length m (max 31) */
    uint32_t state;      /**< Current shift register state */
    int      amplitude;  /**< Amplitude scaling factor */
} sysid_prbs_t;

/** Initialize PRBS generator with given register length.
 *  Tap configuration must yield a maximal-length sequence.
 *  Predefined good configurations: m=5→[5,3], m=7→[7,6], m=10→[10,7], m=15→[15,14]
 */
int  sysid_prbs_init(sysid_prbs_t *prbs, int reg_length, const int *taps,
                     int n_taps, int amplitude);
void sysid_prbs_free(sysid_prbs_t *prbs);

/** Generate next PRBS value (-amplitude or +amplitude) */
int  sysid_prbs_next(sysid_prbs_t *prbs);

/** Generate N samples of PRBS into array.
 *  @param signal  Output array [N], each element = ±amplitude
 *  @param T_clk   Clock period in samples (hold each value T_clk samples)
 */
int  sysid_prbs_generate(sysid_prbs_t *prbs, double *signal, int N, int T_clk);

/** Generate standard PRBS signal (convenience: auto-configures taps) */
int  sysid_prbs_generate_std(int reg_length, double *signal, int N,
                             int T_clk, double amplitude);

/** Clock the LFSR one step (internal use but exposed for testing) */
uint32_t sysid_lfsr_step(uint32_t state, const int *taps, int n_taps);

/*---------------------------------------------------------------------------
 * L6: Random Binary Signal (RBS)
 *     Each sample independently ±amplitude with 50% probability.
 *---------------------------------------------------------------------------*/

/** Generate RBS of length N using a simple LCG */
int  sysid_rbs_generate(double *signal, int N, double amplitude, unsigned int seed);

/*---------------------------------------------------------------------------
 * L6: Multisine signal
 *     u(k) = Σ_{i=1}^{Nf} A_i sin(2π f_i k Ts + φ_i)
 *     Phase optimization (Schroeder, 1970) minimizes crest factor.
 *---------------------------------------------------------------------------*/

/** Multisine specification */
typedef struct {
    double *frequencies;  /**< Frequency vector [Nf] in Hz */
    double *amplitudes;   /**< Amplitude per frequency [Nf] */
    double *phases;       /**< Phase per frequency [Nf] in radians */
    int     Nf;           /**< Number of frequency components */
    double  Ts;           /**< Sampling period */
    double  offset;       /**< DC offset */
} sysid_multisine_t;

/** Allocate and init multisine with given frequencies */
int  sysid_multisine_alloc(sysid_multisine_t *ms, int Nf, double Ts);
void sysid_multisine_free(sysid_multisine_t *ms);

/** Set amplitudes flat (all equal) */
void sysid_multisine_set_flat_amp(sysid_multisine_t *ms, double amplitude);

/** Set phases via Schroeder's method to minimize crest factor:
 *   φ_i = φ_1 - 2π Σ_{j=1}^{i-1} (i-j) P_j
 * where P_j are normalized powers.
 */
void sysid_multisine_set_schroeder_phase(sysid_multisine_t *ms, unsigned int seed);

/** Generate N samples of multisine signal */
int  sysid_multisine_generate(const sysid_multisine_t *ms, double *signal, int N);

/** Compute crest factor = max|x| / rms(x) */
double sysid_crest_factor(const double *signal, int N);

/** Generate log-spaced multisine for frequency-domain identification */
int  sysid_multisine_logspace(int Nf, double f_min, double f_max, double Ts,
                              double amplitude, double *signal, int N);

/*---------------------------------------------------------------------------
 * L6: Chirp / Swept sine signal
 *     u(k) = A sin(2π (f₀ + (f₁-f₀)·k/(2N)) · k · T_s)
 *---------------------------------------------------------------------------*/

/** Generate linear chirp from f0 to f1 over N samples */
int  sysid_chirp_linear(double *signal, int N, double f0, double f1,
                        double Ts, double amplitude);

/** Generate logarithmic chirp (constant relative sweep rate) */
int  sysid_chirp_log(double *signal, int N, double f0, double f1,
                     double Ts, double amplitude);

/** Generate sine sweep with specified time vector */
int  sysid_swept_sine(double *signal, int N, const double *inst_freq,
                      double Ts, double amplitude);

/*---------------------------------------------------------------------------
 * L6: Step and impulse signals
 *---------------------------------------------------------------------------*/

/** Generate step signal: u(k) = 0 for k < step_sample, = amplitude for k ≥ step_sample */
int  sysid_step_signal(double *signal, int N, int step_sample, double amplitude);

/** Generate impulse: u(0) = amplitude, u(k>0) = 0 */
int  sysid_impulse_signal(double *signal, int N, double amplitude);

/** Generate Gaussian white noise N(0, sigma^2) */
int  sysid_gaussian_noise(double *signal, int N, double sigma, unsigned int seed);

/*---------------------------------------------------------------------------
 * L4: Persistence of excitation analysis
 *---------------------------------------------------------------------------*/

/**
 * Compute covariance matrix R_u(n) for order n persistence test
 *   R_ij = (1/N) Σ u(k-i) u(k-j)
 * Returns 1 if PE of order n (positive definite), 0 otherwise.
 */
int  sysid_test_pe_order(const double *u, int N, int order, double *R, double tol);

/** Minimum singular value of R_u(n) — measure of excitation quality */
double sysid_pe_quality(const double *u, int N, int order);

/** Compute input power spectral density estimate via periodogram */
int  sysid_input_psd(const double *u, int N, double *freq, double *psd,
                     int Nfft, double Ts);

#endif /* SYSID_SIGNALS_H */
